name: Test

on: [push]

env:
  GITHUB_USER: ${{ secrets.PACKAGES_USER }}
  GITHUB_TOKEN: ${{ secrets.PACKAGES_TOKEN }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Docker login
        run: echo $GITHUB_TOKEN | docker login docker.pkg.github.com -u $GITHUB_USER --password-stdin

      - name: Test
        run: scripts/test.sh
