name: Test on Every Push

on: [push]

env:
  GITHUB_USERNAME: ${{ secrets.PACKAGES_USER }}
  GITHUB_TOKEN: ${{ secrets.PACKAGES_TOKEN }}

jobs:
  test_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Docker login
        run: echo $PACKAGES_TOKEN | docker login docker.pkg.github.com --username $PACKAGES_TOKEN --password-stdin

      - name: Test
        run: scripts/test.sh
